%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\User\Documents\MATLAB\Senan 5\July15.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/08/08 10:33:39

%% Import the data
[FileName,PathName,FilterIndex] = uigetfile({'*.xlsx';'*.slx';'*.xls'},'Data Selector');
[~, ~, raw] = xlsread([PathName FileName],'Sheet1','A2:B12');

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
ST = data(:,1);
DNI = data(:,2);

%% Clear temporary variables
clearvars data raw;